# Generated by Django 3.2.15 on 2022-08-25 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SatelliteInfo',
            fields=[
                ('id', models.IntegerField(default=0)),
                ('Name', models.CharField(default='NA', max_length=200, primary_key=True, serialize=False)),
                ('OrbitType', models.CharField(blank=True, max_length=200, null=True)),
                ('OrbitDay', models.FloatField(blank=True, max_length=200, null=True)),
                ('OrbitalPeriod', models.FloatField(blank=True, max_length=200, null=True)),
                ('altitude', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SensorName', models.CharField(blank=True, max_length=200, null=True)),
                ('SatelliteName', models.CharField(blank=True, max_length=200, null=True)),
                ('SatelliteID', models.IntegerField(default=0)),
                ('Swath', models.FloatField(default=0)),
                ('TiltFore', models.FloatField(default=0)),
                ('TiltAft', models.FloatField(default=0)),
                ('application1', models.CharField(blank=True, max_length=200, null=True)),
                ('application2', models.CharField(blank=True, max_length=200, null=True)),
                ('application3', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
